version: '3.4'
services:
  conduit:
    restart: always
    image: conduit:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - CD_ACCESS_TOKEN_SECRET_KEY=5h0pp1ng_k4rt
      - CD_PASSWORD_SALT=06!grsnxXG0d*Pj496p6fuA*o
      - CD_APP_ENV=test
